### ISSUE TITLE
Come up with font pairing

### ISSUE THREAD

**Issue by stephendawsondev** [jdhernandezS1/Summer_Hackaton#19]
We need some font pairings for the app. Here's a useful website to help: https://fontjoy.com/

**Comment by secarrel** [comment]
Google Fonts



![Image](https://github.com/jdhernandezS1/Summer_Hackaton/assets/132008003/d151408e-3509-4f38-951e-4677e530cf07)



- 'Sansita' for game heading
- 'Handlee' for personality statements eg. Congratulations/Game tag line/Found it etc. 
- 'ABeeZee' for detailed instructions, challenge info and longer text. 

Is everyone happy with these?

**Comment by stephendawsondev** [comment]
They look good to me!

**Comment by stephendawsondev** [comment]
Once the majority has given their feedback, I think that these can be added the Readme and we can close this issue. 🏆

**Comment by stephendawsondev** [comment]
Completed in #52
